#swagger 配置
swagger:
  title: 消息管理
  desc: 消息管理 API 操作文档
  version: 1.0
  termsOfServiceUrl: http://localhost:8080
  license: Apache 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
  basePackage: com.example.swagger.controller
  groupName: 消息管理API
  contactName: niit
  contactUrl: https://github.com/ziqicongdonglai/SpringBoot.git
  contactEmail: 1826213722@qq.com


